title: Super Start # your name (or website title) here
logo: "/images/Screenshot 2022-01-05 142910.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  The best data scientist out there! 
  <br><br>
  Never stop learning!
  <br><br>
  <a href="https://www.linkedin.com/in/stefanie-schussler">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
